/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import JuegoPrincipal.*;
import NPC.*;
import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class ColocarPlanta extends javax.swing.JDialog {
    
    private static Tablero tableroJuego;
    
    /**
     * Creates new form ColocarPlanta
     */
    public ColocarPlanta(java.awt.Frame parent, boolean modal, Tablero tableroJuego) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.tableroJuego = tableroJuego;
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        plantasList = new javax.swing.JList<>();
        fila = new javax.swing.JTextField();
        columna = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        colocarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        plantasList.setBackground(new java.awt.Color(146, 191, 48));
        plantasList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Girasol", "Lanzaguisantes", "Nuez" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        plantasList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(plantasList);

        fila.setBackground(new java.awt.Color(146, 191, 48));
        fila.setColumns(3);
        fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filaActionPerformed(evt);
            }
        });

        columna.setBackground(new java.awt.Color(146, 191, 48));
        columna.setColumns(3);
        columna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnaActionPerformed(evt);
            }
        });

        jLabel1.setText("Fila");

        jLabel2.setText("Columna");

        colocarButton.setBackground(new java.awt.Color(146, 191, 48));
        colocarButton.setText("Colocar");
        colocarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colocarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(columna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(colocarButton))
                        .addGap(0, 148, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(columna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(colocarButton)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void columnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_columnaActionPerformed

    private void colocarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colocarButtonActionPerformed
        // TODO add your handling code here:
        try {
            
            int filaPos = Integer.valueOf(fila.getText()) ;
            int columnaPos = Integer.valueOf(columna.getText());
            
            if(tableroJuego.getCasillasTablero()[filaPos][columnaPos].isOcupado()) {
                String mensaje = "No puedes colocar aqui una planta";
                JOptionPane.showMessageDialog(this, mensaje, "Error", WIDTH);
                this.dispose();
            }

            String eleccionPlanta = plantasList.getSelectedValue();

            switch(eleccionPlanta) {
                case "Girasol":
                    if (tableroJuego.getSoles() >= 20 && tableroJuego.isPuedeColocarGirasol()) {
                        tableroJuego.colocarGirasol(filaPos, columnaPos);   
                    } else {
                        String mensaje = "No puedes colocar un girasol";
                        JOptionPane.showMessageDialog(this, mensaje, "Error", WIDTH);    
                    }
                    
                    break;
                case "Lanzaguisantes":
                    if (tableroJuego.getSoles() >= 50 && tableroJuego.isPuedeColocarLanzaGuisantes()){
                     tableroJuego.colocarLanzaGuisantes(filaPos, columnaPos);   
                    } else {
                        String mensaje = "No puedes colocar un lanzaguisantes";
                        JOptionPane.showMessageDialog(this, mensaje, "Error", WIDTH);    
                    }
                    break;
                case "Nuez":
                    if (tableroJuego.getSoles() >= 50 && tableroJuego.isPuedeColocarNuez()) {
                     tableroJuego.colocarNuez(filaPos, columnaPos);   
                    }  else {
                        String mensaje = "No puedes colocar una nuez";
                        JOptionPane.showMessageDialog(this, mensaje, "Error", WIDTH);    
                    }
                    
                    break;
            }

            dispose();
            
        } catch (NumberFormatException e) {
            String mensaje = "Introduce un numero correcto en filas y columnas";
            JOptionPane.showMessageDialog(this, mensaje, "Error", WIDTH);
        } catch (NullPointerException e) {
            String mensaje = "Selecciona una clase de Planta";
            JOptionPane.showMessageDialog(this, mensaje, "Error", WIDTH); 
        }

        
         
    }//GEN-LAST:event_colocarButtonActionPerformed

    private void filaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColocarPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColocarPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColocarPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColocarPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ColocarPlanta dialog = new ColocarPlanta(new javax.swing.JFrame(), true, tableroJuego);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colocarButton;
    private javax.swing.JTextField columna;
    private javax.swing.JTextField fila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> plantasList;
    // End of variables declaration//GEN-END:variables
}
